Api created
NicolasMuras/I_N_D_R_A pull request #2
Opened 2021-04-03 21:16 UTC by nachovidondo

I already create an API in Tags and Users App

2021-04-03 21:54 UTC, NicolasMuras requested changes
Review finalizada, espero los cambios

2021-04-03 21:54 UTC, NicolasMuras commented on apps/Tags/api/views/views_tags.py
> +from rest_framework.response import Response
Response no es utilizado en el código, debe ser quitado.

2021-04-03 21:54 UTC, NicolasMuras commented on apps/Tags/models.py
> +    name = models.CharField(max_length=200, verbose_name="Nombre")
Deben añadirse a cada atributo los parámetros: null y blank siguiendo la lógica.

2021-04-03 21:54 UTC, NicolasMuras commented on apps/Tags/tests.py
> +# Create your tests here.
Este archivo no será utilizado, puede ser eliminado.

2021-04-03 21:54 UTC, NicolasMuras commented on apps/Users/api/views/views_user.py
> +from rest_framework.response import Response
Response esta siendo importado pero no es utilizado, debe eliminarse esa linea.

2021-04-03 21:54 UTC, NicolasMuras commented on apps/Users/models.py
> +        verbose_name = "Users"
El verbose_name es incorrecto, el valor correcto es "User" debe agregarse la variable verbose_name_plural y a esta si asignarle el valor "Users" en plural.

2021-04-03 21:54 UTC, NicolasMuras commented on apps/Users/models.py
> +    passsword = models.CharField(
la variable password tiene 3 's' en el nombre, debe corregirse este error de tipeo, se recomienda eliminar las migraciones y volver a migrar luego de esto.

2021-04-03 21:54 UTC, NicolasMuras commented on apps/Users/models.py
> +        max_length=200, verbose_name="Contraseña", blank=True, null=True
El valor blank y null es incorrecto, el usuario no debe poder almacenarse si no se tiene una contraseña, cambiar los valores "True" por "False".

2021-04-03 21:54 UTC, NicolasMuras commented on apps/Users/models.py
> +        max_length=200, verbose_name="Nombre", blank=True, null=True
El valor blank y null es incorrecto, el usuario no debe poder almacenarse si no se tiene un nombre, cambiar los valores "True" por "False".

2021-04-03 21:54 UTC, NicolasMuras commented on apps/Users/tests.py
> +# Create your tests here.
Este archivo debe ser eliminado.

2021-04-03 21:54 UTC, NicolasMuras commented on apps/Users/views.py
> +# Create your views here.
Este archivo no esta siendo utilizado, debe ser eliminado.

2021-04-03 21:54 UTC, NicolasMuras commented on apps/main/forms.py
Este archivo forms debe ser eliminado ya que trabajamos con REST.

2021-04-03 21:54 UTC, NicolasMuras commented on apps/main/views.py
> +from apps.main.forms import UsuarioForm
eliminar este archivo views.py de main, ya que proporcionaremos la vista del index a traves de vue.

2021-04-03 21:54 UTC, NicolasMuras commented on apps/main/urls.py
> +from apps.main.views import schedule_view
eliminar esta linea "from apps.main.views import schedule_view"

2021-04-03 21:54 UTC, NicolasMuras commented on Schedule_Proyect/urls.py
> +    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
Eliminar el código introducido por error aqui.

2021-04-03 21:54 UTC, NicolasMuras requested changes
Review finalizada, espero los cambios

2021-04-03 22:21 UTC, nachovidondo commented on apps/main/urls.py
> +from apps.main.views import schedule_view
por que esta linea?

2021-04-03 22:28 UTC, NicolasMuras requested changes

2021-04-03 22:28 UTC, NicolasMuras commented on apps/Tags/models.py
> +        max_length=200, verbose_name="Nombre", blank=True, null=True
se debe cambiar a "False" todos los valores "True", excepto en priority

2021-04-03 22:28 UTC, NicolasMuras commented on Schedule_Proyect/urls.py
> +from drf_yasg.views import get_schema_view
permissions y get_schema_view no están siendo utilizados, la importación es errónea, re_path tampoco esta siendo utilizado, por lo que no debe ser importado, pasa lo mismo con "openapi"

2021-04-03 22:28 UTC, NicolasMuras commented on apps/main/urls.py
> -from main.views import schedule_view
Se debe eliminar también el path() asociado a schedule_view, ya que no será utilizado.

2021-04-04 14:12 UTC, NicolasMuras approved these changes

2021-04-04 14:36 UTC, NicolasMuras approved these changes

2021-04-04 14:46 UTC, merged